title: Homepage
page-top-title: BIOGRAPHY
top-section-bg-text: Robotics and AI Centre
home-subtitle: Xueliang Cheng&ensp;|&ensp;程学亮
page-topic-title-phd: PhD WORKS
top-section-bg-text_phdworks: Collebrative Aquatic Positioning System
home-subtitle-phdworks: Collebrative Aquatic Positioning System (CAP)
page-topic-title-walle: Wall-E PROJECT